authors = ["Arnaldur <aarnaldur@gmail.com>"]
name = "Processing"
uuid = "67a3e0a2-23bb-11e9-332d-27896587ab55"
version = "0.1.0"

[deps]
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"
